### ISSUE TITLE
TcpChatServer Example - Get list of connected ChatSessions

### ISSUE THREAD

**Issue by matthiasorth** [chronoxor/CSharpServer#6]
I'm looking for a way to get a list of connected ChatSessions in the ChatServer object.
Something like this:

>                   foreach (ChatSession sess in server.ChatSessions) 
>                   {
>                         sess.Send(GetNewMessageFor(sess.Id));
>                   }
> 

Maybe someone can give a hint. Thanks a lot!

**Comment by chronoxor** [comment]
You have two options:
1) Use server.Multicast(...) method to send message to ALL connected sessions
2) You can override server.OnConnected()/server.OnDisconnected() methods in your code and handle sessions. Then you can use server.FindSession(id).Send(...) to send message to some session by its Id.

**Comment by matthiasorth** [comment]
Thanks a lot!

Best regards,
Matthias

**Comment by findli** [comment]
> You have two options:
> 
> 1. Use server.Multicast(...) method to send message to ALL connected sessions
> 2. You can override server.OnConnected()/server.OnDisconnected() methods in your code and handle sessions. Then you can use server.FindSession(id).Send(...) to send message to some session by its Id.

Hi.
Is there a way to get request headers from client( and add headers to initial client request)? Or somehow provide client identity from the client side during establish connection step?

It's only support in NetServer version?
